// Listas estáticas (signos, traços, frases, conselhos)

export const SIGNOS = [
  "Áries","Touro","Gêmeos","Câncer","Leão","Virgem",
  "Libra","Escorpião","Sagitário","Capricórnio","Aquário","Peixes"
];

export const ZODIAC_TRAITS = {
  "Áries":["enérgico","direto","competitivo","ousado","impulsivo","iniciador","corajoso"],
  "Touro":["estável","paciente","sensorial","teimoso","confiável","perseverante","prático"],
  "Gêmeos":["comunicativo","curioso","versátil","inquieto","sociável","intelectual","brincalhão"],
  "Câncer":["protetor","intuitivo","emocional","caseiro","empático","nostálgico","acolhedor"],
  "Leão":["confiante","carismático","criativo","generoso","dramático","orgulhoso","expressivo"],
  "Virgem":["analítico","detalhista","organizado","prático","reservado","metódico","criterioso"],
  "Libra":["diplomático","afável","equilibrado","cauteloso","relacional","indeciso","conciliador"],
  "Escorpião":["intenso","estratégico","reservado","transformador","focado","leal","profundo"],
  "Sagitário":["aventureiro","otimista","direto","filosófico","expansivo","independente","explorador"],
  "Capricórnio":["ambicioso","disciplinado","pragmático","persistente","responsável","sério","focado em metas"],
  "Aquário":["independente","original","idealista","intelectual","visionário","não convencional","humanitário"],
  "Peixes":["empático","imaginativo","intuitivo","sensível","sonhador","artístico","compassivo"]
};

export const TRAITS_POOL = [
  'Estratégico','Independente','Cético','Planejamento de longo prazo','Calmo no caos',
  'Analítico','Curioso','Observador','Experimentador','Abstrato',
  'Decisivo','Organizador','Direto','Orientado a metas','Eficiente',
  'Debatedor','Contrário lúdico','Gerador de ideias','Raciocínio rápido','Inquieto',
  'Idealista','Reservado','Busca padrões','Orientado a propósito','Comedido',
  'Valores fortes','Imaginativo','Sensível','Autêntico','Reflexivo',
  'Apoia o grupo','Persuasivo','Articula redes','Visão ampla','Encorajador',
  'Entusiasta','Espontâneo','Conector','Otimista','Exploratório',
  'Responsável','Metódico','Detalhista','Prático','Comprometido',
  'Atencioso','Constante','Serviço ao outro','Cuidadoso','Confiável',
  'Estruturado','Sem rodeios','Coordenador','Foco em resultados','Ordeiro',
  'Comunitário','Afetuoso','Organizado','Anfitrião','Tradicional',
  'Mão na massa','Frio sob pressão','Resolve problemas','Poucas palavras','Adaptável',
  'Criativo discreto','Estético','Gentil','Foco no presente','Flexível',
  'Ação rápida','Pragmático','Corajoso','Improvisa','Vibrante',
  'Expressivo','Gosta de gente','Brincalhão','Aqui e agora','Energético'
];

// 90 frases (resumidas aqui por brevidade; acrescente todas se quiser 1:1)
export const HORO = [
 "Um ciclo se repete sem pedir licença",
  "As respostas surgem quando você não procura",
  "O silêncio abre espaço para outra voz",
  "O que parecia distante se aproxima de repente",
  "O detalhe esquecido revela a cena inteira",
  "Uma escolha antiga ressurge disfarçada",
  "O tempo curva intenções e endireita caminhos",
  "Um gesto simples ecoa além do esperado",
  "A espera esconde mais movimento que a pressa",
  "O que não foi dito pesa mais do que palavras",
  "A sombra acompanha, mas não ameaça",
  "O inesperado se acomoda como rotina",
  "A repetição revela o que a novidade esconde",
  "O vazio se mostra fértil quando olhado de perto",
  "A incerteza se veste de convicção",
  "O destino sorri quando você desvia o olhar",
  "O mapa se redesenha no passo improvisado",
  "Uma ausência preenche mais que uma presença",
  "O improvável encontra lugar no habitual",
  "O atraso revela a cadência necessária",
  "O aparente caos se organiza por trás da cortina",
  "O caminho mais curto dobra em espiral",
  "A dúvida sustenta mais do que certezas frágeis",
  "Um eco distante responde antes da pergunta",
  "A pausa prolonga o alcance do gesto",
  "A confusão abre espaço para novas formas",
  "O simples se revela intrincado ao olhar atento",
  "O acaso oferece o que o esforço não garante",
  "Um desvio discreto conduz ao centro",
  "O ontem se disfarça de amanhã",
  "O detalhe perdido retorna em outro contexto",
  "A clareza chega quando não é mais necessária",
  "O vazio ilumina contornos invisíveis",
  "A sombra revela a forma da luz",
  "O fim anuncia outro começo mascarado",
  "A contradição se mantém estável",
  "Um suspiro muda o ritmo da maré",
  "O improvável insiste até se tornar natural",
  "A pressa cega o que a espera revela",
  "O sinal aparece disfarçado de ruído",
  "A lembrança se confunde com premonição",
  "O acaso observa quando você não nota",
  "O labirinto se endireita ao ser percorrido",
  "A dúvida acompanha como guia secreto",
  "Um passo em falso alinha o caminho",
  "O erro abre portais improváveis",
  "O invisível sustenta o visível",
  "A contradição alimenta o equilíbrio",
  "A espera prolonga a chegada do óbvio",
  "O trivial se colore de mistério ao entardecer",
  "Um ciclo inacabado se insinua novamente",
  "O esquecido se apresenta como novidade",
  "A calma prepara o terreno do inesperado",
  "O som do nada chama atenção",
  "Um instante carrega mais do que um ano",
  "O improvável repousa na superfície comum",
  "O tempo brinca de esconder",
  "O gesto pequeno decide grandes direções",
  "A maré muda sem aviso",
  "O previsto falha no detalhe crucial",
  "O silêncio carrega respostas sutis",
  "Um ruído revela a melodia oculta",
  "O acaso dança com a disciplina",
  "A rotina guarda brechas de surpresa",
  "A dúvida se disfarça de certeza passageira",
  "O instante esquecido ganha protagonismo",
  "O improvável amadurece como fruta tardia",
  "Um vazio inesperado se mostra fértil",
  "O erro indica a porta correta",
  "O trivial disfarça a revelação",
  "Um ciclo finda e retorna disfarçado",
  "A espera é apenas outro tipo de movimento",
  "O detalhe se amplia até cobrir o todo",
  "O esquecido retorna com nova voz",
  "O contraste revela o contorno essencial",
  "O que se repete muda na sutileza",
  "Um sopro altera a rota fixa",
  "A sombra se alonga para mostrar direção",
  "A pausa revela o compasso secreto",
  "O imprevisto se torna inevitável",
  "A certeza se dissolve em nova pergunta",
  "O comum se veste de extraordinário",
  "Um tropeço muda o rumo sem esforço",
  "O que parecia fixo se dobra sem quebrar",
  "O silêncio carrega mais peso que palavras",
  "O tempo desdobra o que parecia inteiro",
  "O improvável persiste até convencer",
  "O óbvio se esconde na penumbra",
  "Um gesto antigo retorna renovado",
  "A ausência marca mais do que a presença",
  "A contradição abre espaço para conciliação"
];

export const ADVICE = [
  "Cuide do básico hoje: dormir bem, comer simples e mover o corpo.",
  "Anote uma preocupação e escreva ao lado: o que posso fazer em 10 minutos?",
  "Envie uma mensagem de agradecimento para alguém que te ajudou recentemente.",
  "Desligue notificações por 30 minutos e termine uma tarefa pequena por completo.",
  "Se algo parecer pesado, reduza o escopo pela metade e avance mesmo assim.",
  "Leia duas páginas de um livro que você já queria começar.",
  "Beba água antes do café e faça três respirações mais profundas que o normal.",
  "Diga não a um pedido hoje para dizer sim a algo importante para você.",
  "Escolha um ponto da casa para arrumar por 5 minutos; celebre o feito.",
  "Faça uma caminhada curta sem fones e observe três coisas novas no caminho.",
  "Revise seu dia em uma frase: o que avançou, por menor que seja?",
  "Pergunte-se: o que posso simplificar agora sem perder qualidade?",
  "Alongue-se por dois minutos antes de olhar o celular.",
  "Faça uma pausa consciente antes de responder a algo importante.",
  "Experimente ouvir uma música sem fazer mais nada.",
  "Anote três coisas pelas quais você é grato hoje.",
  "Defina uma micro-tarefa que pode ser concluída em menos de 5 minutos.",
  "Caminhe alguns passos a mais do que o necessário.",
  "Faça contato visual e sorria para alguém hoje.",
  "Respire fundo três vezes antes de abrir um aplicativo.",
  "Deixe um copo de água já cheio ao lado da cama para amanhã.",
  "Revise uma lista antiga e risque algo já concluído.",
  "Saia de casa e observe o céu por um minuto.",
  "Troque um hábito automático por uma escolha consciente.",
  "Escreva uma frase positiva para si mesmo.",
  "Desligue uma aba desnecessária do navegador.",
  "Anote uma ideia mesmo que pareça boba.",
  "Escolha uma tarefa e faça com atenção plena.",
  "Arrume um pequeno canto do seu espaço de trabalho.",
  "Leia uma frase inspiradora em voz alta.",
  "Coloque alarme para beber água a cada 2 horas.",
  "Evite discutir por algo que pode ser resolvido amanhã.",
  "Deixe o celular de lado durante uma refeição.",
  "Pergunte a alguém como ela realmente está.",
  "Escreva uma lista curta de prioridades para o dia.",
  "Evite multitarefas por 15 minutos seguidos.",
  "Respire fundo antes de entrar em uma reunião.",
  "Elimine um item que está te distraindo.",
  "Escute sua música favorita inteira sem pular.",
  "Deixe a luz natural entrar em casa.",
  "Levante-se e caminhe durante uma ligação.",
  "Reveja uma meta e ajuste um passo menor para chegar nela.",
  "Escreva uma pergunta que você quer responder até o fim da semana.",
  "Leia uma notícia devagar em vez de apenas rolar o feed.",
  "Separe cinco objetos para doar ou descartar.",
  "Dê bom dia para alguém que não espera.",
  "Relembre uma conquista recente, por menor que seja.",
  "Troque o café da tarde por uma fruta.",
  "Dedique cinco minutos a algo criativo.",
  "Faça algo com a mão não dominante.",
  "Olhe pela janela e perceba três cores diferentes.",
  "Mova o corpo ao som de uma música curta.",
  "Anote uma preocupação e escreva uma possível solução ao lado.",
  "Feche os olhos por 30 segundos e apenas respire.",
  "Agradeça alguém por uma ajuda passada.",
  "Arrume sua mesa antes de encerrar o dia.",
  "Relembre um sonho e anote o que sentir.",
  "Evite a primeira reação automática em uma conversa.",
  "Faça algo devagar de propósito hoje.",
  "Escolha não opinar sobre um assunto irrelevante.",
  "Permita-se 5 minutos de silêncio absoluto.",
  "Planeje uma pequena recompensa para o final do dia."
];
