// src/lib/weatherAdviceTexts.js
export const WEATHER_ADVICE = {
  // Base por categoria (pode adicionar/editar à vontade)
  sunny: [
    "Aproveite a luz natural: faça uma caminhada curta e respire fora da tela.",
    "Se puder, faça uma pausa ao ar livre; 10 minutos de sol já fazem diferença.",
    "Trabalhe perto da janela e recarregue energia com a luz do dia.",
    "Está ensolarado: aproveite a luz do sol para uma caminhada de 10 minutos.",
    "Com sol forte, trabalhe perto da janela e faça pausas curtas ao ar livre.",
    "Dia de sol: use protetor e defina uma micro-meta antes de sair.",
    "Céu aberto: hidrate-se e faça um alongamento rápido ao sol.",
    "Sol presente: faça uma ligação caminhando na sombra do quarteirão.",
    "Ensolarado lá fora: abra as cortinas e respire fundo 5 vezes.",
    "Com sol, leia duas páginas ao ar livre e volte energizado.",
    "Sol firme: caminhe sem fone por 8 minutos e observe o caminho.",
    "Ensolarado e claro: planeje uma tarefa curta e conclua na luz do dia.",
    "Sol na área: fotografe o céu, compartilhe com alguém e retome o foco.",
    "Sol radiante: escreva 3 coisas boas do seu dia e guarde para reler depois.",
    "Ensolarado: sente-se por 2 minutos ao sol e pratique respiração profunda.",
    "Dia claro: faça uma pausa curta e organize sua mesa em silêncio.",
    "Com sol forte: caminhe até a padaria ou mercado sem pressa e observe o entorno.",
    "Luz intensa lá fora: anote uma meta rápida e risca ao concluir.",
    "Ensolarado e quente: aproveite para beber água gelada e refrescar a mente.",
    "Sol firme no céu: saia por 5 minutos e apenas observe as sombras mudando.",
    "Céu ensolarado: faça uma pequena lista de gratidão enquanto olha para fora.",
    "Sol forte: escreva uma ideia rápida no bloco de notas e volte ao foco.",
    "Dia iluminado: alongue o pescoço olhando para o céu.",
    "Com sol firme: caminhe devagar e observe três detalhes novos na rua.",
    "Ensolarado: sorria para alguém e note a reação.",
    "Sol radiante: faça uma pausa para beber água com calma.",
    "Luz clara: leia uma frase inspiradora e respire fundo.",
    "Dia ensolarado: olhe para fora e descreva mentalmente o que vê.",
    "Sol intenso: feche os olhos e sinta o calor por 20 segundos.",
    "Céu aberto: escreva um objetivo pequeno e cumpra ainda hoje.",
    "Sol brilhante: mande uma mensagem curta de agradecimento a alguém.",
    "Ensolarado: abra a janela e deixe o ar circular por 2 minutos.",
    "Sol firme: tire 5 minutos para pensar sem olhar o celular.",
    "Com sol lá fora: caminhe até um ponto próximo e volte renovado.",
    "Dia claro: faça um registro rápido no diário ou planner.",
    "Sol presente: sorria sozinho, só para sentir a energia mudar.",
    "Luz de sol: organize um item da mesa de trabalho.",
    "Ensolarado: respire contando até 4 e solte contando até 6, três vezes.",
    "Dia de sol: planeje o próximo intervalo antes de retomar o foco.",
    "Sol firme: estique braços e pernas por 1 minuto inteiro.",
    "Céu ensolarado: fotografe uma árvore e salve como inspiração.",
    "Sol no alto: caminhe pelo quarteirão sem olhar o celular.",
    "Dia ensolarado: feche os olhos e ouça os sons ao redor.",
    "Sol radiante: escreva três palavras que resumem seu humor.",
    "Luz natural: ajuste a cadeira ou postura e alongue a coluna.",
    "Sol firme: pense em uma vitória recente, por menor que seja.",
    "Céu aberto: organize uma aba ou pasta no computador.",
    "Ensolarado: beba água devagar enquanto olha para fora.",
    "Sol forte: faça uma ligação curta ao invés de enviar mensagem.",
    "Dia claro: dedique 3 minutos para limpar sua mesa.",
    "Sol brilhante: sorria olhando o reflexo no espelho.",
    "Com sol: ande descalço em casa por alguns instantes.",
    "Sol firme: anote um aprendizado do dia até agora.",
    "Dia de sol: faça 10 agachamentos ou polichinelos.",
    "Sol intenso: olhe para uma planta ou flor e observe os detalhes.",
    "Céu ensolarado: guarde 2 minutos para silêncio total.",
    "Sol aberto: escreva uma meta em uma folha solta e cole à vista.",
    "Dia iluminado: ajuste a iluminação da sala para mais naturalidade.",
    "Sol firme: pense em algo bom do passado e sorria.",
    "Com sol: ouça uma música curta e volte renovado.",
    "Sol presente: faça uma caminhada curta e repare nas sombras.",
    "Dia claro: desenhe algo rápido em um papel qualquer.",
    "Sol brilhante: mande um emoji de sol para alguém no chat.",
    "Luz solar: observe o movimento das nuvens por 1 minuto.",
    "Sol forte: escolha um pequeno objeto e mude de lugar.",
    "Ensolarado: escreva uma frase positiva no seu caderno.",
    "Dia de sol: olhe para o horizonte e relaxe os ombros.",
    "Sol radiante: levante, respire fundo e alongue os braços.",
    "Céu aberto: organize mentalmente as três próximas tarefas.",
    "Sol firme: imagine uma cor e procure vê-la ao redor.",
    "Dia ensolarado: faça uma pausa breve e agradeça por algo simples.",
    "O sol tá brilhando, mas você ainda tá apagado?",
    "Se nem a luz do dia te anima, o que vai?",
    "O sol nasceu faz horas, e sua meta ainda dorme.",
    "Ensolarado não é convite pra preguiça.",
    "Enquanto você reclama do calor, alguém já aproveitou a manhã.",
    "O dia claro não clareia desculpas.",
    "Se até o sol aparece todo dia, por que você não?",
    "O brilho lá fora só expõe sua falta de ação.",
    "Não adianta abrir a cortina se você não abre a agenda.",
    "Sol sem atitude não esquenta resultado.",
    "O céu azul não elimina sua lista de tarefas.",
    "O sol ilumina, mas quem decide andar é você.",
    "Ensolarado não significa produtivo, isso depende de você.",
    "O sol não espera, e seu prazo também não.",
    "Se até a sombra se move, qual sua desculpa?",
    "Um dia ensolarado é um convite para renovar suas energias; use a luz natural como lembrete de que cada tarefa concluída abre espaço para outra conquista.",
    "Abra a janela e deixe o sol iluminar não apenas o ambiente, mas também seus pensamentos e intenções.",
    "A clareza do céu pode inspirar a clareza nas suas prioridades; aproveite para organizar seu dia com foco.",
    "Caminhar sob o sol, mesmo que por alguns minutos, pode transformar seu humor e abrir novas ideias.",
    "O sol mostra que há luz mesmo após noites longas; siga em frente, porque nada é permanente.",
    "A energia solar aquece a pele e também pode aquecer sua motivação; use esse impulso para começar.",
    "O brilho do dia ensolarado é como uma tela em branco, esperando suas ações para colorir a jornada.",
    "Aproveite a vitalidade que o sol transmite para dar início a um projeto que estava guardado.",
    "Ensolarado é sinônimo de clareza; permita-se enxergar soluções simples para problemas que pareciam complexos.",
    "O calor do dia pode ser traduzido em entusiasmo; use isso como combustível.",
    "Cada raio de sol pode ser visto como um lembrete de que você tem novas chances de começar.",
    "Um dia claro favorece novas perspectivas; caminhe e observe o que talvez passasse despercebido.",
    "O céu limpo pode refletir uma mente mais leve; esvazie a cabeça e recomece.",
    "Use a energia do sol para dar ritmo ao dia e concluir uma tarefa com mais prazer.",
    "O sol que aquece também pode trazer calma; respire fundo e sinta o equilíbrio entre energia e serenidade.",
    "Ensolarado é oportunidade de olhar para fora e para dentro, encontrando gratidão em pequenos detalhes.",
    "Permita-se ser iluminado por ideias, assim como a luz ilumina cada canto da cidade.",
    "Caminhar sob a luz natural é uma forma simples de recarregar sua vitalidade e foco.",
    "O dia ensolarado traz frescor ao espírito; trate suas tarefas como sementes que florescem nessa luz.",
    "Use o sol como lembrete de constância: ele nasce todos os dias; faça o mesmo com sua disciplina.",
   ],
  cloudy: [
    "Use o clima neutro para foco: escolha uma tarefa e termine sem interrupções.",
    "A luz difusa é ótima para criar: escreva ou esboce por 15 minutos.",
    "Faça uma caminhada leve; o céu nublado ajuda a manter o ritmo.",
    "Está nublado: aproveite a luz difusa para foco em uma tarefa sem interrupções.",
    "Céu encoberto: faça um brainstorm de 10 ideias em 10 minutos.",
    "Com tempo nublado, organize sua mesa por 5 minutos e recomece limpo.",
    "Nublado lá fora: caminhe no quarteirão para manter o ritmo sem calor.",
    "Céu cinza: escolha uma prioridade e conclua um bloco de 25 minutos.",
    "Tempo fechado: aqueça com uma bebida quente e revise sua lista.",
    "Nublado constante: escreva um parágrafo que você estava adiando.",
    "Sem sol forte: faça alongamento de pescoço e ombros por 2 minutos.",
    "Céu nublado: desligue notificações por 30 minutos e termine algo pequeno.",
    "Luz suave de dia nublado: leia duas páginas e aplique uma ideia.",
    "Clima nublado: use o silêncio para revisar suas anotações.",
    "Céu cinzento: escreva três tarefas e conclua a primeira agora.",
    "Tempo fechado: organize um arquivo digital parado há semanas.",
    "Luz difusa: dedique 10 minutos para resolver algo simples.",
    "Nublado: faça uma pausa curta e organize seus pensamentos no papel.",
    "Céu encoberto: responda uma mensagem pendente com objetividade.",
    "Clima neutro: aproveite e finalize algo que evita há dias.",
    "Nublado lá fora: ajuste seu espaço de trabalho e continue focado.",
    "Céu cinza: pratique respiração lenta por 3 ciclos completos.",
    "Tempo nublado: anote uma ideia e estruture um próximo passo.",
    "Luz suave: reserve 15 minutos para leitura produtiva.",
    "Sem sol: limpe sua caixa de e-mails por 5 minutos.",
    "Céu fechado: escreva uma frase de motivação no caderno.",
    "Nublado constante: faça uma pausa para chá ou café consciente.",
    "Clima neutro: planeje o restante da sua tarde em 3 pontos.",
    "Luz cinza: aproveite para revisar uma tarefa já concluída.",
    "Tempo encoberto: caminhe dentro de casa por 2 minutos.",
    "Nublado: pense em algo positivo e anote no diário.",
    "Céu fechado: desligue o celular por 20 minutos e foque.",
    "Luz difusa: revise sua agenda da semana e ajuste.",
    "Sem sol forte: organize os atalhos do seu computador.",
    "Nublado lá fora: escreva uma ideia criativa sem filtro.",
    "Céu cinza: conclua um bloco de 25 minutos de estudo.",
    "Clima neutro: aproveite para revisar documentos pendentes.",
    "Tempo encoberto: faça um exercício leve de alongamento.",
    "Luz suave: leia uma notícia ou artigo útil por 5 minutos.",
    "Nublado: medite por 2 minutos observando a respiração.",
    "Céu cinzento: ouça uma música calma e volte ao foco.",
    "Clima fechado: conclua algo pequeno antes do almoço.",
    "Nublado constante: abra um caderno e esboce uma ideia.",
    "Luz difusa: organize pastas físicas ou digitais por 10 minutos.",
    "Céu encoberto: tome um copo de água lentamente e respire.",
    "Sem sol forte: faça 5 minutos de revisão de metas.",
    "Nublado: planeje uma pequena recompensa ao terminar uma tarefa.",
    "Céu cinza: caminhe até outro cômodo e volte energizado.",
    "Tempo fechado: revise as anotações do último encontro.",
    "Luz suave: escreva três pontos de gratidão do dia.",
    "Nublado constante: desligue notificações por meia hora.",
    "Céu encoberto: escolha uma aba aberta e finalize a leitura.",
    "Clima neutro: organize mentalmente seu próximo passo.",
    "Sem sol forte: esvazie a lixeira do computador e respire.",
    "Nublado: ligue para alguém que você queria atualizar.",
    "Céu cinzento: faça uma pausa breve e beba água.",
    "Tempo fechado: prepare um checklist para amanhã.",
    "Luz difusa: escolha um artigo e destaque ideias principais.",
    "Nublado lá fora: estique braços e pernas por 2 minutos.",
    "Céu encoberto: leia um parágrafo inspirador e continue.",
    "Clima neutro: reserve 5 minutos para limpar sua mesa.",
    "Sem sol: abra um arquivo antigo e atualize uma parte.",
    "Nublado: conclua algo fácil para ganhar ritmo.",
    "O céu tá cinza, mas seu foco não precisa ser.",
    "Nublado não é igual a improdutivo.",
    "Se o dia não tem cor, coloque ação nele.",
    "Não é o tempo que tá pesado, é sua falta de atitude.",
    "Enquanto o sol não aparece, sua desculpa aparece rápido.",
    "O dia fechado não fecha sua lista de tarefas.",
    "O céu cinza é só cenário, não sentença.",
    "Nublado é o clima, não sua mente.",
    "O tempo encoberto não encobre sua preguiça.",
    "Não espere o sol voltar pra começar a andar.",
    "O dia sem brilho só reflete sua falta de movimento.",
    "Céu cinza não apaga prazo vermelho.",
    "Se está nublado lá fora, clareie dentro de casa.",
    "O tempo pode estar parado, mas você não pode.",
    "Nublado é só cor de fundo, quem decide a cena é você.",
    "O céu cinza não apaga sua energia; aproveite o tom neutro para focar no que importa.",
    "Um dia nublado pode trazer a calma necessária para mergulhar em tarefas profundas.",
    "A luz difusa é um convite à concentração sem distrações externas.",
    "O clima fechado pode ser cenário ideal para clareza interna.",
    "Aproveite a ausência de sol forte para se concentrar sem pressa.",
    "Nublado é sinônimo de neutralidade; transforme isso em foco equilibrado.",
    "O céu encoberto pode ser a tela perfeita para você escrever o seu dia.",
    "O tom cinza do céu pode realçar a cor das suas conquistas pessoais.",
    "Nublado lá fora, mas claro dentro: defina sua prioridade principal.",
    "Um dia fechado pode ser a oportunidade para abrir novas ideias.",
    "A suavidade da luz nublada pode trazer serenidade às suas ações.",
    "Menos distrações externas, mais espaço para seu próprio ritmo.",
    "O clima nublado pede organização; use isso a seu favor.",
    "Nublado é tempo de introspecção produtiva.",
    "A falta de sol pode ser compensada pela luz da sua disciplina.",
    "O céu cinzento pode ajudar você a manter-se constante sem pressa.",
    "Um dia nublado pode se tornar um campo fértil para ideias silenciosas.",
    "Aproveite a monotonia do clima para gerar movimento interno.",
    "Nublado é só o pano de fundo; a cor do dia é você quem define.",
    "O tempo fechado pode ser visto como convite à concentração absoluta.",
  ],
  rainy: [
      "Está chovendo: leve guarda-chuva e ajuste seu trajeto com calma.",
      "Chuva na área: priorize tarefas internas e conclua um bloco curto agora.",
      "Garoa constante: use calçado impermeável e evite pressa nas saídas.",
      "Pancadas de chuva: reagende deslocamentos não essenciais e foque no que dá.",
      "Chuvoso e úmido: organize um canto da casa por 5 minutos.",
      "Chuva forte: revise compromissos, crie um plano B e siga com segurança.",
      "Tempo chuvoso: faça um treino leve em casa e volte ao foco.",
      "Chuva lá fora: escreva um diário curto enquanto ouve o som da água.",
      "Garoando: verifique previsões, escolha janela de saída e mantenha o guarda-chuva à mão.",
      "Chuva intermitente: faça backup de algo importante e marque como concluído.",
      "Dia chuvoso: prepare uma bebida quente e revise sua lista de tarefas.",
      "Chuva leve: faça uma pausa curta e organize sua mesa.",
      "Tempo molhado: conclua algo digital que estava pendente.",
      "Garoa fina: leia duas páginas de um livro dentro de casa.",
      "Chuva constante: desligue notificações e foque por 25 minutos.",
      "Dia úmido: caminhe devagar em casa e alongue o corpo.",
      "Pancadas de chuva: responda mensagens pendentes com calma.",
      "Chuva forte: aproveite o som para escrever ideias soltas.",
      "Tempo chuvoso: organize pastas digitais por 10 minutos.",
      "Garoando: dedique 5 minutos para meditar ouvindo a chuva.",
      "Chuva lá fora: prepare um lanche simples e volte renovado.",
      "Dia molhado: faça uma pausa e ligue para alguém querido.",
      "Chuva intermitente: revise compromissos do calendário.",
      "Tempo úmido: cuide de uma planta dentro de casa.",
      "Chuva leve: escreva três coisas pelas quais é grato.",
      "Dia chuvoso: conclua uma tarefa curta adiada ontem.",
      "Garoa: limpe a caixa de entrada por 5 minutos.",
      "Chuva constante: organize os arquivos da área de trabalho.",
      "Dia úmido: faça alongamento de pescoço e ombros.",
      "Chuva forte: aproveite para planejar o restante da semana.",
      "Chuva lá fora: escreva um parágrafo criativo no diário.",
      "Tempo chuvoso: conclua uma tarefa doméstica simples.",
      "Chuva fina: ouça uma música calma e retome o foco.",
      "Dia molhado: faça uma lista curta de prioridades.",
      "Chuva intermitente: cuide de pequenas pendências online.",
      "Tempo úmido: organize gaveta ou armário por 10 minutos.",
      "Chuva leve: desligue telas por 5 minutos e respire fundo.",
      "Dia chuvoso: leia um artigo curto e aplique uma ideia.",
      "Garoando: tome água morna e faça uma pausa consciente.",
      "Chuva constante: crie uma anotação de meta rápida.",
      "Chuva forte: aproveite para esboçar novos planos.",
      "Tempo úmido: caminhe dentro de casa sem pressa.",
      "Chuva leve: revise notas antigas e atualize.",
      "Dia molhado: cuide da roupa ou do ambiente interno.",
      "Chuva intermitente: conclua um checklist pequeno.",
      "Garoando: separe algo para descarte ou doação.",
      "Chuva constante: revise projetos longos em blocos curtos.",
      "Tempo chuvoso: feche os olhos e ouça a chuva por 1 minuto.",
      "Dia úmido: organize uma pasta de fotos digitais.",
      "Chuva forte: defina um plano B para amanhã.",
      "Chuva lá fora: use o tempo para escrever rascunhos.",
      "Dia molhado: atualize seu planner ou agenda.",
      "Chuva intermitente: faça backup de arquivos recentes.",
      "Tempo chuvoso: escreva uma mensagem de incentivo a alguém.",
      "Garoa: aproveite para ler uma citação inspiradora.",
      "Chuva constante: limpe a mesa de trabalho rapidamente.",
      "Chuva forte: finalize algo pequeno antes da pausa.",
      "Dia úmido: prepare chá ou café e relaxe por 2 minutos.",
      "Tempo chuvoso: organize mentalmente as tarefas do dia.",
      "A chuva não atrasa só ônibus, atrasa também quem usa como desculpa.",
      "O barulho da chuva relaxa, mas não entrega projeto.",
      "Se está chovendo lá fora, trabalhe mais firme aqui dentro.",
      "A água cai, mas sua disciplina não pode cair junto.",
      "A chuva não cancela suas metas, só sua vontade fraca.",
      "Enquanto você espera parar de chover, sua lista só cresce.",
      "O guarda-chuva protege da água, não da procrastinação.",
      "Chuva não é motivo, é só cenário.",
      "A tempestade lá fora não é nada comparada ao atraso na sua mesa.",
      "Se até a rua se enche, por que sua agenda tá vazia?",
      "A chuva limpa o chão, mas não limpa pendência.",
      "Enquanto você olha a janela, alguém tá entregando resultado.",
      "A água cai em litros, mas sua ação em gotas.",
      "A chuva é forte, mas sua desculpa é fraca.",
      "O temporal passa, o arrependimento fica.",
      "A chuva pode parecer um convite à pausa, mas também é uma chance de introspecção e foco interno.",
      "O som da água caindo pode se tornar trilha sonora para sua concentração.",
      "Enquanto a cidade desacelera, você pode encontrar no ritmo da chuva o compasso ideal para concluir suas metas.",
      "O clima chuvoso pede aconchego, e dentro dele pode nascer a produtividade silenciosa.",
      "Aproveite a chuva para olhar para dentro e reorganizar prioridades.",
      "A água limpa o chão, e você pode aproveitar para limpar sua mente.",
      "Se o céu está carregado, alivie seu próprio peso concluindo algo simples.",
      "A chuva convida ao recolhimento, mas também abre espaço para criatividade florescer.",
      "O barulho da chuva pode ser o lembrete perfeito para desacelerar e focar no essencial.",
      "Chuva lá fora, clareza por dentro: organize pensamentos e avance.",
      "Aproveite o clima chuvoso para ler algo que inspire novas ideias.",
      "O cinza do céu pode ser pano de fundo para a cor das suas conquistas.",
      "A chuva acalma a cidade; deixe que acalme também sua mente.",
      "Use o tempo chuvoso para revisitar projetos antigos e dar novos passos.",
      "O ambiente fechado pode se transformar em espaço de foco absoluto.",
      "Enquanto a água cai, suas ideias podem fluir melhor do que nunca.",
      "O clima chuvoso pode ser a pausa natural que você precisava para refletir.",
      "Chuva é sinônimo de renovação; aproveite para se renovar também.",
      "Aproveite o aconchego do dia chuvoso para cultivar gratidão em pequenas coisas.",
      "O barulho da chuva pode embalar sua concentração como uma música de fundo natural.",
        ],

  // Frases universais (não precisam falar de clima)
  generic: [
    
    "Defina uma micro-meta de 15 minutos e feche um ciclo pequeno ainda hoje.",
    "Beba água agora e faça três respirações profundas antes da próxima tarefa.",
    "Revise sua lista e elimine um item que não faz mais sentido.",
    "Faça uma pausa curta sem tela e observe algo fora da janela.",
    "Comece o dia com um copo de água.",
    "Organize sua mesa antes de iniciar o trabalho.",
    "Respire fundo três vezes antes de responder a algo importante.",
    "Escreva sua prioridade número 1 do dia em um papel.",
    "Caminhe cinco minutos entre tarefas longas.",
    "Evite olhar o celular nos primeiros 10 minutos ao acordar.",
    "Leia uma página de um livro em vez de rolar o feed.",
    "Pergunte a alguém como ela realmente está.",
    "Anote uma ideia que passou pela sua mente.",
    "Faça uma pausa curta sem telas.",
    "Alongue-se por dois minutos antes de continuar.",
    "Beba água antes de tomar café.",
    "Elimine uma aba inútil no navegador.",
    "Diga 'não' para algo que não importa.",
    "Escreva uma frase positiva para si mesmo.",
    "Troque um hábito automático por uma escolha consciente.",
    "Escute sua música favorita até o fim.",
    "Faça contato visual ao conversar.",
    "Agradeça alguém por um gesto simples.",
    "Relembre uma conquista recente.",
    "Escolha uma tarefa pequena e conclua totalmente.",
    "Planeje uma pequena recompensa para o final do dia.",
    "Dê um passo a mais do que o necessário.",
    "Olhe para o céu por um minuto.",
    "Escreva três coisas pelas quais você é grato.",
    "Ande sem fones por alguns minutos.",
    "Guarde algo que está fora do lugar.",
    "Evite multitarefas por 15 minutos seguidos.",
    "Respire fundo antes de abrir um app automático.",
    "Diga 'bom dia' para alguém inesperado.",
    "Revise sua lista e risque um item feito.",
    "Anote uma preocupação e escreva ao lado uma ação possível.",
    "Levante-se e caminhe durante uma ligação.",
    "Escreva uma pergunta que quer responder até o fim da semana.",
    "Faça algo devagar de propósito.",
    "Separe três objetos para doar.",
    "Feche os olhos por 30 segundos e apenas respire.",
    "Tire cinco minutos para algo criativo.",
    "Evite discutir sobre algo irrelevante.",
    "Escute em silêncio uma música calma.",
    "Relembre um sonho da noite passada.",
    "Diminua o escopo de algo pesado pela metade.",
    "Faça algo com a mão não dominante.",
    "Escreva uma frase inspiradora em voz alta.",
    "Apague uma notificação inútil.",
    "Leia uma notícia devagar em vez de só rolar.",
    "Escolha um canto da casa e arrume por 5 minutos.",
    "Lembre-se: você não precisa resolver tudo hoje.",
    "Desligue o celular durante uma refeição.",
    "Sorria para alguém sem motivo especial.",
    "Escreva três intenções para amanhã antes de encerrar o dia.",
    "Desconecte-se das redes por 10 minutos.",
    "Ouça atentamente alguém sem interromper.",
    "Dê um pequeno passo em algo que vem adiando.",
    "Alongue os braços olhando para o teto.",
    "Leia uma citação e reflita por 1 minuto.",
    "Experimente anotar suas ideias em tópicos curtos.",
    "Arrume uma gaveta esquecida.",
    "Respire fundo antes de abrir seus e-mails.",
    "Escreva uma pergunta curiosa para pesquisar depois.",
    "Diminua a velocidade ao caminhar até o próximo cômodo.",
    "Experimente ficar em silêncio por dois minutos.",
    "Escreva o que já conseguiu hoje em vez do que falta.",
    "Troque de lugar um objeto da mesa para renovar o ambiente.",
    "Faça uma pausa para alongar os dedos das mãos.",
    "Leia o título de três livros ou artigos e escolha um.",
    "Escreva uma meta em uma frase curta e visível.",
    "Desligue notificações por meia hora.",
    "Respire contando até quatro e solte contando até oito.",
    "Caminhe até a janela e observe algo novo.",
    "Escreva uma palavra que resuma seu humor.",
    "Planeje um intervalo breve no meio da tarde.",
    "Arrume apenas uma prateleira.",
    "Escute o som ambiente por um minuto.",
    "Faça algo que leve menos de cinco minutos agora.",
    "Coloque água fresca ao lado da sua mesa.",
    "Anote três ideias sem julgá-las.",
    "Estique as pernas por um minuto em pé.",
    "Anote um microaprendizado do dia.",
    "Feche os olhos e repare no som mais distante.",
    "Escreva duas coisas que gostaria de simplificar.",
    "Reorganize os ícones da área de trabalho.",
    "Escreva o próximo passo de um projeto em andamento.",
    "Ajuste a postura ao se sentar.",
    "Envie uma mensagem curta de incentivo para alguém.",
    "Leia um parágrafo e sublinhe uma ideia.",
    "Defina um limite de tempo para terminar a próxima tarefa.",
    "Anote três coisas que gostaria de fazer sem pressa.",
    "Troque de posição a cadeira ou a tela.",
    "Escreva algo que possa ser descartado hoje.",
    "Inspire pelo nariz e solte pela boca lentamente.",
    "Experimente ficar dois minutos sem fazer nada.",
    "Relembre uma memória que traz calma.",
    "Organize a mochila ou bolsa.",
    "Anote uma frase para reler amanhã cedo.",
    "Refaça um checklist de forma simplificada.",
    "Diminua o ritmo de uma tarefa e perceba o processo.",
    "Escolha algo para não fazer hoje.",
    "Anote uma prioridade da semana em letras grandes.",
    "Deixe sua mesa pronta para o próximo início de trabalho.",
    "Não é o clima que trava você, é a sua indecisão.",
    "O dia já começou; a pergunta é se você começou também.",
    "Se sobrou tempo pra reclamar, sobrou tempo pra agir.",
    "Não existe ‘amanhã melhor’, só hoje mal aproveitado.",
    "A disciplina não muda com a previsão do tempo.",
    "Se não fizer agora, vai sobrar peso pro você de amanhã.",
    "Foco não aparece sozinho, você tem que chamar.",
    "Enquanto você pensa, outros já estão fazendo.",
    "O clima é externo, mas a decisão é interna.",
    "Procrastinar é só escolher se afogar devagar.",
    "A meta não se cumpre porque você suspirou; é porque você agiu.",
    "Até o pior dia tem 24 horas; o que você vai fazer com elas?"   ,   
    "Ninguém lembra do esforço, só do resultado entregue.",
    "O tempo não para — mas você parou?",
    "Ou você faz hoje, ou hoje faz você.",
    "Escolha um começo gentil: respire, revise o dia e eleja a ação que trará maior alívio quando concluída.",
    "Transforme ansiedade em lista: escreva passos simples e avance o primeiro agora.",
    "Celebre microvitórias: reconheça o que já fez e use esse impulso como combustível para a próxima tarefa.",
    "Quando tudo parecer grande, reduza o escopo até caber em 15 minutos e comece.",
    "Permita-se imperfeito: feito e melhorável vale mais que perfeito e ausente.",
    "Relembre seu porquê: conecte a tarefa de hoje ao impacto que importa para você.",
    "Crie um bloco de foco protegido: silencie distrações e trate-o como compromisso consigo.",
    "Troque autocrítica por curiosidade: pergunte ‘o que posso testar agora?’ em vez de ‘por que não consigo?’.",
    "Planeje pausas de cuidado: água, alongamento e um respiro consciente mantêm a constância.",
    "Escolha uma coisa para dizer não hoje e libere espaço para o que é essencial.",
    "Converse com alguém de confiança: compartilhar o plano aumenta clareza e compromisso.",
    "Comece pequeno, continue constante: 1% por dia transforma qualquer projeto.",
    "Converta preocupação em protocolo: defina gatilhos, ações e critérios de encerramento.",
    "Feche ciclos: termine algo iniciado antes de abrir uma nova frente.",
    "Use linguagem que empodera: troque ‘tenho que’ por ‘eu escolho’ e repare a diferença.",
    "Faça uma revisão compassiva: aprenda com ontem sem se punir, ajuste e siga.",
    "Visualize o próximo estado concluído e dê o primeiro passo que o torna inevitável.",
    "Defina um fim claro para o dia: um ritual simples sinaliza descanso e previne carga mental.",
    "Organize energia, não só tempo: encaixe tarefas desafiadoras nas horas em que você rende mais.",
    "Lembre-se: progresso é direcional; se estiver avançando, já está no caminho certo.",
  ],

  // Complementos condicionais (apendam à base quando fizer sentido)
  modifiers: {
    hot: [
      "Evite os horários de pico do sol; hidrate-se e use protetor.",
      "Prefira sombra e mantenha uma garrafinha de água por perto.",
      "Evite os horários de pico do sol; hidrate-se e use protetor.",
      "Prefira sombra e mantenha uma garrafinha de água por perto.",
      "Use roupas leves e respiráveis para maior conforto.",
      "Faça pausas curtas em locais frescos sempre que possível.",
      "Evite exercícios intensos sob sol forte.",
      "Leve um chapéu ou boné para proteção extra.",
      "Reforce a hidratação com frutas ricas em água.",
      "Abra janelas cedo e feche durante o calor do dia.",
      "Se possível, trabalhe em ambientes ventilados.",
      "Use toalhas úmidas para refrescar a pele.",
      "Programe atividades físicas para cedo ou fim do dia.",
      "Evite ficar em locais sem circulação de ar.",
      "Reduza a cafeína para não desidratar.",
      "Use protetor solar mesmo em pequenas saídas.",
      "Mantenha pets hidratados e em locais frescos.",
      "Carregue garrafa de água sempre que sair.",
      "Priorize refeições leves e nutritivas.",
      "Se sentir fadiga, faça pausas à sombra.",
      "Evite exposição direta em superfícies quentes.",
      "Organize o dia em blocos curtos para não sobrecarregar.",
      "Tá calor? Reclamar não refresca, beber água sim.",
      "O sol não vai esperar você se mexer.",
      "Se der pra ficar no celular, dá pra levantar e esticar também.",
      "Não é o calor que atrapalha, é a sua desculpa.",
      "O suor seca, mas a tarefa parada não termina.",
      "Você não é sorvete, não vai derreter.",
      "Se está difícil sair, faça dentro de casa mesmo.",
      "O calor não é desculpa pra não cuidar de si.",
      "Quer refrescar? Termine logo o que precisa.",
      "Enquanto você pensa no calor, a lista só cresce.",
      "O corpo pede sombra, mas sua mente precisa de ação.",
      "Reclamar do clima não risca nada da lista.",
      "Até o ar-condicionado não faz milagre sem disciplina.",
      "Tá quente, mas você ainda pode se mover.",
      "Ou você domina o dia, ou o calor domina você.",
      "O calor intenso é um lembrete para desacelerar e cuidar do corpo, sem deixar de lado suas metas.",
      "Use a energia do dia quente para transformar esforço em conquista.",
      "Em dias quentes, hidrate-se e mantenha sua disciplina firme.",
      "O calor pode ser desconfortável, mas também pode ser combustível para agir com intensidade.",
      "Se o sol exige cuidado, suas tarefas também pedem atenção.",
      "Transforme o suor em símbolo de dedicação e não de desistência.",
      "O calor do dia é a prova de que sua força também pode se expandir.",
      "Mesmo no calor, a constância é o que traz frescor ao resultado final.",
      "Aproveite a vitalidade que o clima quente desperta para dar passos firmes.",
      "O calor exige leveza: leveza nas roupas, nas escolhas e nas metas.",
      "Deixe o calor ser apenas cenário, não desculpa.",
      "O dia quente pode te lembrar que disciplina gera frutos mesmo sob pressão.",
      "O sol forte reforça a importância de pausar, hidratar e continuar.",
      "O calor pede adaptação, mas não paralisação.",
      "Suor é parte do processo de quem se move em direção ao objetivo.",
      "Use o dia quente como prova da sua capacidade de resiliência.",
      "O calor é oportunidade de testar sua constância em condições desafiadoras.",
      "Assim como o sol é intenso, seja intenso no que realmente importa.",
      "Mesmo em dias escaldantes, pequenas ações constroem grandes resultados.",
      "Deixe que o calor desperte energia, não desculpas.",
    ],
    cold: [
      "Aqueça o corpo com alongamento rápido ou uma bebida quente.",
      "Use camadas extras antes de sair.",
      "Aqueça o corpo com alongamento rápido ou uma bebida quente.",
      "Use camadas extras antes de sair.",
      "Proteja mãos e pés com acessórios adequados.",
      "Aproveite o frio para atividades internas de foco.",
      "Inicie o dia com aquecimento leve para circular energia.",
      "Use cachecol ou gola para proteger a respiração.",
      "Mantenha ambientes internos bem aquecidos.",
      "Carregue luvas para trajetos longos.",
      "Se possível, faça pausas com bebidas quentes.",
      "Vista roupas que mantenham o calor sem apertar.",
      "Evite roupas molhadas, troque-as rapidamente.",
      "Aqueça o ambiente com luz natural ao abrir cortinas.",
      "Priorize atividades que mantenham o corpo em movimento.",
      "Use meias grossas para conforto prolongado.",
      "Se for caminhar, escolha calçados antiderrapantes.",
      "Alongue os ombros e o pescoço para ativar circulação.",
      "Leve uma camada extra para emergências.",
      "Prefira sopas e refeições quentes.",
      "Mantenha boa hidratação, mesmo no frio.",
      "Use o frio como incentivo para desacelerar e focar.",
      "O frio não vai trabalhar por você.",
      "Se ficar parado, vai esfriar mais ainda.",
      "O casaco esquenta, mas não resolve suas pendências.",
      "Não é hibernação, é segunda-feira.",
      "O frio é só desculpa pra adiar de novo?",
      "Levantar já é o primeiro aquecimento.",
      "Você não precisa de mais coberta, precisa de atitude.",
      "O frio não congela a sua disciplina.",
      "Seus objetivos não esperam a primavera.",
      "Ficar enrolado não gera resultado.",
      "O café aquece, mas não entrega seu trabalho.",
      "Se está gelado, mova-se. Simples.",
      "Enquanto você treme, as tarefas acumulam.",
      "Ninguém lembra do frio depois da meta cumprida.",
      "O frio passa, mas a lista fica.",
      "O frio convida ao recolhimento, mas também pode ser o cenário ideal para foco interno.",
      "Aqueça o corpo com movimento e aqueça a mente com disciplina.",
      "Use a sensação de frio como lembrete de que ação gera calor.",
      "Enquanto o corpo pede descanso, sua meta pede consistência.",
      "O frio pode desacelerar, mas não precisa paralisar.",
      "A cada passo no frio, você prova que está disposto a ir além do conforto.",
      "A brisa gelada pode trazer clareza e frescor às suas ideias.",
      "O frio é só o pano de fundo, não o dono do seu ritmo.",
      "Aproveite o clima frio para criar espaços aconchegantes de produtividade.",
      "O frio externo pode ser enfrentado com o calor da sua disciplina.",
      "Quando o corpo resiste ao frio, a mente pode florescer com esforço.",
      "O inverno não é pausa, é teste de constância.",
      "O frio reforça que nem sempre o ambiente ajuda, mas sua decisão pode superar.",
      "Em dias frios, escolha aquecer-se com movimento e propósito.",
      "A temperatura baixa é convite para desacelerar com qualidade, não para parar.",
      "Use o frio como metáfora de desafios: passageiro, mas sempre superável.",
      "A cada respiração no ar gelado, lembre-se de que está vivo para agir.",
      "O frio reforça a importância de aquecer não só o corpo, mas também os planos.",
      "Em dias de frio, cada passo é prova de determinação.",
      "O frio é cenário de introspecção, mas também de ação disciplinada.",
    ],
    windy: [
      "Prefira rotas mais abrigadas do vento.",
      "Se ficar em casa, faça pausas ativas curtas.",
      "Prefira rotas mais abrigadas do vento.",
      "Se ficar em casa, faça pausas ativas curtas.",
      "Segure bem objetos leves que podem voar.",
      "Use roupas que protejam os ouvidos do vento.",
      "Aproveite para ventilar a casa com janelas controladas.",
      "Proteja olhos com óculos contra poeira.",
      "Evite carregar papéis soltos em ambientes externos.",
      "Amarre cabelos longos para maior conforto.",
      "Verifique se portas e janelas estão bem fechadas.",
      "Se dirigir, mantenha firmeza extra no volante.",
      "Escolha roupas justas para reduzir incômodo do vento.",
      "Evite guarda-chuvas frágeis em rajadas fortes.",
      "Reduza atividades externas em áreas abertas.",
      "Aproveite para caminhar em áreas mais arborizadas.",
      "Verifique alertas meteorológicos de rajadas.",
      "Use mochila em vez de bolsas de mão.",
      "Adapte treinos externos para ambientes internos.",
      "Escute sons do vento como pausa consciente.",
      "Proteja objetos em varandas e quintais.",
      "Use o vento como lembrete de flexibilidade no dia.",
      "O vento bagunça o cabelo, mas não sua rotina.",
      "Se até o vento está correndo, por que você não?",
      "Rajada não derruba quem já está em movimento.",
      "Segurar desculpa pesa mais que segurar guarda-chuva.",
      "O vento muda o caminho, não o objetivo.",
      "O barulho lá fora não justifica a inércia dentro.",
      "Deixe o vento levar a preguiça, não seu foco.",
      "Se o vento assusta, imagina o prazo estourado.",
      "Não adianta fechar a janela e abrir mão da meta.",
      "O vento não empurra quem não se move.",
      "A ventania passa, mas sua disciplina fica.",
      "Você não é folha pra ficar à deriva.",
      "Até o vento se adapta, e você?",
      "O vento tira o equilíbrio de quem já está parado.",
      "Quem tem meta firme não balança com rajada.",
      "O vento pode balançar as árvores, mas não precisa balançar sua determinação.",
      "A ventania é movimento externo; você decide o movimento interno.",
      "Deixe o vento levar distrações, não sua disciplina.",
      "Assim como as folhas voam, solte também o que não importa.",
      "O vento é instável, mas você pode ser constante.",
      "Cada rajada pode ser usada como impulso, não como obstáculo.",
      "O barulho do vento é convite para ouvir melhor sua própria voz.",
      "O vento bagunça o cenário, mas pode clarear ideias novas.",
      "Se o vento muda a rota, adapte-se sem perder o destino.",
      "O clima ventoso mostra que nem sempre temos controle externo, mas sempre temos interno.",
      "Aproveite a ventania como lembrete de flexibilidade.",
      "Assim como o vento muda, você também pode mudar de estratégia.",
      "Deixe que o vento limpe velhas ideias e abra espaço para novas.",
      "O vento não pede permissão para soprar; não peça permissão para agir.",
      "Se tudo parece instável, seja o ponto firme dentro da ventania.",
      "O vento não atrapalha quem já está em movimento.",
      "Rajadas lembram que a vida é feita de ciclos; aproveite cada um.",
      "Se o vento balança, use-o como sinal de que é hora de ajustar velas.",
      "A ventania pode ser barulho, mas você pode ser constância.",
      "Deixe que o vento seja trilha sonora do seu próximo passo.",
    ],
    "heavy-rain": [
      "Se puder, reduza saídas não essenciais hoje.",
      "Ajuste o plano e priorize segurança no trajeto.",
      "Se puder, reduza saídas não essenciais hoje.",
      "Ajuste o plano e priorize segurança no trajeto.",
      "Verifique previsão antes de sair para evitar imprevistos.",
      "Leve guarda-chuva reforçado para pancadas fortes.",
      "Aproveite o tempo chuvoso para organizar tarefas internas.",
      "Adapte deslocamentos e saia apenas quando necessário.",
      "Revise compromissos e considere alternativas online.",
      "Evite áreas propensas a alagamento.",
      "Use calçados impermeáveis para mais segurança.",
      "Leve capa de chuva em trajetos longos.",
      "Aproveite para se concentrar em leituras ou estudos.",
      "Revise lista de pendências dentro de casa.",
      "Faça pausas com bebidas quentes enquanto chove.",
      "Use a chuva como trilha sonora para escrever.",
      "Seja flexível com horários em dias chuvosos.",
      "Prepare-se para atrasos no transporte público.",
      "Use a pausa da chuva para pequenas saídas rápidas.",
      "Adie compromissos externos não urgentes.",
      "Planeje o dia com rotas alternativas em mente.",
      "Veja a chuva como convite para foco interno.",
      "A chuva cai, mas sua lista continua seca.",
      "Se a água atrapalha a rua, não precisa atrapalhar você.",
      "Enquanto chove lá fora, você decide se produz ou não.",
      "Chuva não cancela disciplina.",
      "Se o barulho da água te relaxa, use isso pra focar.",
      "O guarda-chuva não resolve suas pendências.",
      "Não culpe a chuva pela sua procrastinação.",
      "Se é dia de chuva, que seja também de entrega.",
      "A tempestade passa, mas o atraso fica.",
      "Chuva forte não é desculpa pra ficar parado.",
      "Enquanto o mundo desacelera, você pode adiantar.",
      "A água lava a rua, mas não limpa sua agenda.",
      "Se o trânsito atrasa, use o tempo pra outra coisa.",
      "A chuva não molha metas bem cuidadas.",
      "Ou você foca agora, ou só vai sobrar enxugar estrago."
    ],
  },
};
