// src/lib/weatherAdviceTexts.js
export const WEATHER_ADVICE = {
  // Base por categoria (pode adicionar/editar à vontade)
  sunny: [
    "Aproveite a luz natural: faça uma caminhada curta e respire fora da tela.",
    "Se puder, faça uma pausa ao ar livre; 10 minutos de sol já fazem diferença.",
    "Trabalhe perto da janela e recarregue energia com a luz do dia.",
    "Está ensolarado: aproveite a luz do sol para uma caminhada de 10 minutos.",
    "Com sol forte, trabalhe perto da janela e faça pausas curtas ao ar livre.",
    "Dia de sol: use protetor e defina uma micro-meta antes de sair.",
    "Céu aberto: hidrate-se e faça um alongamento rápido ao sol.",
    "Sol presente: faça uma ligação caminhando na sombra do quarteirão.",
    "Ensolarado lá fora: abra as cortinas e respire fundo 5 vezes.",
    "Com sol, leia duas páginas ao ar livre e volte energizado.",
    "Sol firme: caminhe sem fone por 8 minutos e observe o caminho.",
    "Ensolarado e claro: planeje uma tarefa curta e conclua na luz do dia.",
    "Sol na área: fotografe o céu, compartilhe com alguém e retome o foco."
  ],
  cloudy: [
    "Use o clima neutro para foco: escolha uma tarefa e termine sem interrupções.",
    "A luz difusa é ótima para criar: escreva ou esboce por 15 minutos.",
    "Faça uma caminhada leve; o céu nublado ajuda a manter o ritmo.",
    "Está nublado: aproveite a luz difusa para foco em uma tarefa sem interrupções.",
    "Céu encoberto: faça um brainstorm de 10 ideias em 10 minutos.",
    "Com tempo nublado, organize sua mesa por 5 minutos e recomece limpo.",
    "Nublado lá fora: caminhe no quarteirão para manter o ritmo sem calor.",
    "Céu cinza: escolha uma prioridade e conclua um bloco de 25 minutos.",
    "Tempo fechado: aqueça com uma bebida quente e revise sua lista.",
    "Nublado constante: escreva um parágrafo que você estava adiando.",
    "Sem sol forte: faça alongamento de pescoço e ombros por 2 minutos.",
    "Céu nublado: desligue notificações por 30 minutos e termine algo pequeno.",
    "Luz suave de dia nublado: leia duas páginas e aplique uma ideia."
  ],
  rainy: [
      "Está chovendo: leve guarda-chuva e ajuste seu trajeto com calma.",
      "Chuva na área: priorize tarefas internas e conclua um bloco curto agora.",
      "Garoa constante: use calçado impermeável e evite pressa nas saídas.",
      "Pancadas de chuva: reagende deslocamentos não essenciais e foque no que dá.",
      "Chuvoso e úmido: organize um canto da casa por 5 minutos.",
      "Chuva forte: revise compromissos, crie um plano B e siga com segurança.",
      "Tempo chuvoso: faça um treino leve em casa e volte ao foco.",
      "Chuva lá fora: escreva um diário curto enquanto ouve o som da água.",
      "Garoando: verifique previsões, escolha janela de saída e mantenha o guarda-chuva à mão.",
      "Chuva intermitente: faça backup de algo importante e marque como concluído."
  ],

  // Frases universais (não precisam falar de clima)
  generic: [
    "Defina uma micro-meta de 15 minutos e feche um ciclo pequeno ainda hoje.",
    "Beba água agora e faça três respirações profundas antes da próxima tarefa.",
    "Revise sua lista e elimine um item que não faz mais sentido.",
    "Faça uma pausa curta sem tela e observe algo fora da janela.",
    "Comece o dia com um copo de água.",
    "Organize sua mesa antes de iniciar o trabalho.",
    "Respire fundo três vezes antes de responder a algo importante.",
    "Escreva sua prioridade número 1 do dia em um papel.",
    "Caminhe cinco minutos entre tarefas longas.",
    "Evite olhar o celular nos primeiros 10 minutos ao acordar.",
    "Leia uma página de um livro em vez de rolar o feed.",
    "Pergunte a alguém como ela realmente está.",
    "Anote uma ideia que passou pela sua mente.",
    "Faça uma pausa curta sem telas.",
    "Alongue-se por dois minutos antes de continuar.",
    "Beba água antes de tomar café.",
    "Elimine uma aba inútil no navegador.",
    "Diga 'não' para algo que não importa.",
    "Escreva uma frase positiva para si mesmo.",
    "Troque um hábito automático por uma escolha consciente.",
    "Escute sua música favorita até o fim.",
    "Faça contato visual ao conversar.",
    "Agradeça alguém por um gesto simples.",
    "Relembre uma conquista recente.",
    "Escolha uma tarefa pequena e conclua totalmente.",
    "Planeje uma pequena recompensa para o final do dia.",
    "Dê um passo a mais do que o necessário.",
    "Olhe para o céu por um minuto.",
    "Escreva três coisas pelas quais você é grato.",
    "Ande sem fones por alguns minutos.",
    "Guarde algo que está fora do lugar.",
    "Evite multitarefas por 15 minutos seguidos.",
    "Respire fundo antes de abrir um app automático.",
    "Diga 'bom dia' para alguém inesperado.",
    "Revise sua lista e risque um item feito.",
    "Anote uma preocupação e escreva ao lado uma ação possível.",
    "Levante-se e caminhe durante uma ligação.",
    "Escreva uma pergunta que quer responder até o fim da semana.",
    "Faça algo devagar de propósito.",
    "Separe três objetos para doar.",
    "Feche os olhos por 30 segundos e apenas respire.",
    "Tire cinco minutos para algo criativo.",
    "Evite discutir sobre algo irrelevante.",
    "Escute em silêncio uma música calma.",
    "Relembre um sonho da noite passada.",
    "Diminua o escopo de algo pesado pela metade.",
    "Faça algo com a mão não dominante.",
    "Escreva uma frase inspiradora em voz alta.",
    "Apague uma notificação inútil.",
    "Leia uma notícia devagar em vez de só rolar.",
    "Escolha um canto da casa e arrume por 5 minutos.",
    "Lembre-se: você não precisa resolver tudo hoje.",
    "Desligue o celular durante uma refeição.",
    "Sorria para alguém sem motivo especial."
  ],

  // Complementos condicionais (apendam à base quando fizer sentido)
  modifiers: {
    hot: [
      "Evite os horários de pico do sol; hidrate-se e use protetor.",
      "Prefira sombra e mantenha uma garrafinha de água por perto.",
    ],
    cold: [
      "Aqueça o corpo com alongamento rápido ou uma bebida quente.",
      "Use camadas extras antes de sair.",
    ],
    windy: [
      "Prefira rotas mais abrigadas do vento.",
      "Se ficar em casa, faça pausas ativas curtas.",
    ],
    "heavy-rain": [
      "Se puder, reduza saídas não essenciais hoje.",
      "Ajuste o plano e priorize segurança no trajeto.",
    ],
  },
};
